### PR TITLE
Enumerables

### PR DESCRIPTION
**Pull request by Chike1990**
We created a script file to house new methods we created and added our new methods onto the existing Enumerable module

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @Chike1990 :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [ ] Your linter check is failing. Kindly fix it.
* [ ] You're expected to add **a descriptive** README file to your repositories as described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

#### Some of your custom enumerable methods are failing some test cases. See them below:

#### my_each_with_index
- [ ] when a block is given when self is an array behaves like #each_with_index calls the given block once for each element in self
- [ ] when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- [ ] when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
#### my_all
- [ ] returns true if the block never returns false or nil
- [ ] returns false if the block returns either false or nil
- [ ] returns false if the block returns either false or nil::range
- [ ] it should not mutate the original array
- [ ] when no block or argument is given returns true when none of the collection members are false or nil
- [ ] when no block or argument is given returns false when one of the collection members are false or nil
- [ ] when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- [ ] when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- [ ] when a class is passed as an argument returns false if any of the collection is not a member of such class
- [ ] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] when a Regex is passed as an argument returns false if any of the collection does not match the Regex
- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- [ ] when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
#### my_any
- [ ] returns true if the block ever returns a value other than false or nil
- [ ] returns false if the block ever returns either false or nil
- [ ] returns false if the block ever returns either false or nil::range
- [ ] does not mutate the original array
- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] when no block or argument is given returns false if at least one of the collection is not true
- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
- [ ] when a Regex is passed as an argument returns true if any of the collection matches the Regex
- [ ] when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- [ ] when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern
#### my_none
- [ ] returns true if the block never returns true for all elements
- [ ] returns false if the block ever returns true for all elements
- [ ] returns false if the block ever returns true for all elements::range
- [ ] does not mutate the original array
- [ ] when no block or argument is given returns true only if none of the collection members is true
- [ ] when no block or argument is given returns false only if one of the collection members is true
- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
- [ ] when a class is passed as an argument returns false if any of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true if none of the collection matches the Regex
- [ ] when a Regex is passed as an argument returns false if any of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ] when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern
#### my_count
- [ ] returns the number of items in enum through enumeration
- [ ] returns the number of items in enum through enumeration::range
- [ ] counts the number of items in enum that are equal to item if an argument is given
- [ ] counts the number of elements yielding a true value if a block is given
- [ ] does not mutate the original array
#### my_map
- [ ] returns a new array with the results of running a given block once for every element in enum.
- [ ] returns a new array with the results of running a given block once for every element in enum.
- [ ] returns a new array with the results of running a given block once for every element in enum::range
- [ ] returns an enumerator if no block is given
- [ ] accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum.
- [ ] executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
- [ ] does not mutate the original array
#### my_inject
- [ ] raises a "LocalJumpError" when no block or argument is given
- [ ] searches for the longest word in an array of strings
- [ ] does not mutate the original array
- [ ] when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
- [ ] when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range
- [ ] when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
- [ ] when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- [ ] when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- [ ] when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- [ ] when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range
#### multiply_els
- [ ] accepts an array as an argument and multiplies all the elements of the array together using #my_inject



## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by Chike1990** [comment]
I have not done all the corrections indicated by the previous reviewer. It's still in progress... I just want to submit what I did this week. Thanks

**Review by taiwo2 — CHANGES_REQUESTED** [review]
Good Job

Am really sorry for the inconvenience, I reviewed you code  and I forgot to left a comment. Am really sorry for the inconvenience it its might have caused to you.
kindly implement all what the previous code reviewer requested, once done submit for another  review.

**Comment by Chike1990** [comment]
Thanks!

Chibuike

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
#Required changes 🛑
**Hey @Chike1990, You have done a good job so far, almost all the tests are passing.** Let's just fix few issues before we can move.

- [ ]  Correct the my_each_with_index method, remember this method should accept two parameters, value, and array index. This is the only method failing.

- [ ]  Remove the multiply_els method from the module and put it outside the module, below the rubocop enable metrics line. This method is just for testing.
**[OPTIONAL]**
- [ ] The readme file is not well-formatted.

**Comment by Chike1990** [comment]
Alright. Thanks

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# Status: Changes Required :tada: 

# Hey Chike1990. 
Welldone for the job done , however out of 79 test cases 3 failed, for us to approve this project, all cases must passed. kindly implement what the previous code reviewer suggested, Here are the changes to make .
Failed examples:

# my_each_with_index 

- my_each_with_index when a block is given when self is an array behaves like each_with_index calls the given block once for each element in self
- my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self

- [ ] Remember about descriptive README file - feel free to use this [template](https://github.com/microverseinc/readme-template)

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED :green_circle: :clap: 
---------
Hello, @Chike1990 @Genius8 great job working on the required changes. you did a pretty good job in this project :muscle: :1st_place_medal: 
---------------
To keep in mind: 
- [ ] [OPTIONAL] On your readme file you don't have a live demo. kindly delete it. 
- [ ] [OPTIONAL] On your readme you have a `getting started` section. Delete this section because you write the steps on the `setup` section. Please either delete section `getting started` or move the steps into `getting started`  and delete the `setup` section.
 These gonna make loos your project more professional. 
-------------------
Now you can merge this branch. :clap: :muscle: 
HAPPY CODING!! AND GOOD LUCK EITH THE COMMING ONES :crossed_fingers: :four_leaf_clover:

**Pull request merged**
